using MauiReactor;
using Microsoft.Maui.Graphics;

namespace WorkoutSample.Resources.Styles;

// Palette generated by the maui-app-design skill.
// Mood: energetic / friendly -> warm primary, complementary teal accent.
// Harmony: complementary (primary hue ~18 deg orange, accent ~190 deg teal).
// Every text/background pair here passes WCAG AA (see DESIGN.md for the table).
// Reactor renders from this Theme; Resources/Styles/Colors.xaml mirrors it for
// anyone consuming the app the plain-XAML way.
class ApplicationTheme : Theme
{
    // Brand
    public static Color Primary { get; } = Color.FromArgb("#C6410F");      // deep orange
    public static Color PrimaryDark { get; } = Color.FromArgb("#F0895C");  // desaturated + lighter for dark theme
    public static Color Accent { get; } = Color.FromArgb("#0E7C86");       // complementary teal
    public static Color AccentDark { get; } = Color.FromArgb("#4FC4D6");
    public static Color Secondary { get; } = Color.FromArgb("#F2A03D");    // warm amber, used sparingly

    // Neutrals (warm-tinted, never pure black/white)
    public static Color Background { get; } = Color.FromArgb("#F7F5F2");
    public static Color BackgroundDark { get; } = Color.FromArgb("#1A1712");
    public static Color Surface { get; } = Color.FromArgb("#FFFFFF");
    public static Color SurfaceDark { get; } = Color.FromArgb("#24211B");
    public static Color TextPrimary { get; } = Color.FromArgb("#1E1B18");
    public static Color TextPrimaryDark { get; } = Color.FromArgb("#ECE8E2");
    public static Color TextSecondary { get; } = Color.FromArgb("#6B6560");
    public static Color TextSecondaryDark { get; } = Color.FromArgb("#A39D95");

    // Semantic
    public static Color Success { get; } = Color.FromArgb("#2E8B57");
    public static Color Warning { get; } = Color.FromArgb("#E8A317");
    public static Color Error { get; } = Color.FromArgb("#D2402F");

    // Single corner radius (friendly = 12) and spacing scale (4/8/12/16/24/32).
    public const int CornerRadius = 12;

    private static bool IsDark => Microsoft.Maui.Controls.Application.Current?.RequestedTheme == AppTheme.Dark;

    public static Color OnBackground => IsDark ? TextPrimaryDark : TextPrimary;
    public static Color OnBackgroundMuted => IsDark ? TextSecondaryDark : TextSecondary;
    public static Color PageBackground => IsDark ? BackgroundDark : Background;
    public static Color CardBackground => IsDark ? SurfaceDark : Surface;
    public static Color BrandPrimary => IsDark ? PrimaryDark : Primary;
    public static Color BrandAccent => IsDark ? AccentDark : Accent;
    public static Color OnBrand => IsDark ? BackgroundDark : Colors.White;

    protected override void OnApply()
    {
        // Styles are expressed directly in the components for this small sample.
    }
}
